import Head from 'next/head';
import useSWR from 'swr';
import { Flex, Heading, SimpleGrid, Text } from '@chakra-ui/react';
import { useId, useMemo } from 'react';
import { Game } from '@/types/Game';
import { GameCard } from '@/components/GameCard';
import { Loading } from '@/components/Loading';

export default function Home() {
  const { data, error, isLoading } = useSWR(['/hot', { type: 'boardgame' }]);
  const gameKey = useId();
  // console.log({ data, error, isLoading });

  const normalizedData: Game[] = useMemo(
    () =>
      data?.items?.item?.map((game: any) => ({
        id: game._attributes.id,
        rank: game._attributes.rank,
        thumbnail: game.thumbnail._attributes.value,
        name: game.name._attributes.value,
        yearpublished: game.yearpublished._attributes.value,
      })) ?? [],
    [data]
  );

  return (
    <>
      <Head>
        <title>The hottest boardgames right now</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex as="main" flex="1" direction="column" gap="4">
        <Heading as="h1" size="2xl" textAlign="center" paddingTop="4">
          The hottest board games right now
        </Heading>
        {isLoading ? <Loading /> : null}
        {error ? <Text>{error}</Text> : null}
        <SimpleGrid
          as="ul"
          spacing="4"
          padding="4"
          maxW="50rem"
          width="100%"
          marginLeft="auto"
          marginRight="auto"
          columns={[1, 2, 3]}
        >
          {data
            ? normalizedData.map((game, i: number) => (
                <GameCard key={game.id} game={game} />
              ))
            : null}
        </SimpleGrid>
      </Flex>
    </>
  );
}
